/* The following code was generated by JFlex 1.4.3 on 25/03/23 05:47 PM */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 25/03/23 05:47 PM from the specification file
 * <tt>D:/ricar/Documents/UP/8/Compiladores/Compiladores-R/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\3\22\0\1\3\1\57\1\7\1\4"+
    "\1\0\1\54\1\55\1\6\1\62\1\63\1\51\1\50\1\3\1\47"+
    "\1\72\1\52\12\2\1\0\1\70\1\46\1\61\1\60\2\0\1\42"+
    "\3\71\1\40\1\41\5\71\1\43\1\71\1\45\3\71\1\36\1\44"+
    "\1\35\1\37\5\71\1\66\1\0\1\67\1\53\1\1\1\0\1\15"+
    "\1\24\1\14\1\22\1\20\1\33\1\12\1\30\1\13\1\71\1\32"+
    "\1\10\1\25\1\16\1\11\1\26\1\71\1\21\1\34\1\17\1\23"+
    "\1\71\1\31\1\27\2\71\1\64\1\56\1\65\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\2\1\17\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\1\3\14\1\6"+
    "\1\1\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\5\1\0\1\24\1\0\1\25\1\0\1\25\1\5"+
    "\1\26\1\27\16\5\1\30\1\6\1\31\1\2\1\32"+
    "\1\33\1\34\1\14\1\0\1\24\1\0\6\5\1\35"+
    "\6\5\1\36\3\5\1\0\4\5\1\37\1\40\4\5"+
    "\1\41\2\5\1\42\10\5\1\43\1\44\1\5\1\45"+
    "\4\5\1\46\1\47\1\50\1\5\1\51\1\52\1\53"+
    "\3\5\1\54\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\73\0\u0127\0\u0162"+
    "\0\u019d\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4\0\u02ff\0\u033a"+
    "\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7\0\u0512"+
    "\0\u054d\0\u0588\0\u05c3\0\u05c3\0\73\0\u05fe\0\u0639\0\u0674"+
    "\0\u06af\0\u06ea\0\u06af\0\73\0\73\0\73\0\73\0\73"+
    "\0\73\0\73\0\u0725\0\u0760\0\u079b\0\u0127\0\u0127\0\u0162"+
    "\0\u0162\0\u07d6\0\u0811\0\u01d8\0\u084c\0\u0887\0\u08c2\0\u08fd"+
    "\0\u0938\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5"+
    "\0\u0b10\0\u0b4b\0\u01d8\0\73\0\73\0\u0b86\0\73\0\73"+
    "\0\73\0\73\0\u0bc1\0\u0bfc\0\u0c37\0\u0c72\0\u0cad\0\u0ce8"+
    "\0\u0d23\0\u0d5e\0\u0d99\0\u01d8\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85"+
    "\0\u0ec0\0\u0efb\0\u01d8\0\u0f36\0\u0f71\0\u0fac\0\u0fe7\0\u1022"+
    "\0\u105d\0\u1098\0\u10d3\0\u01d8\0\u01d8\0\u110e\0\u1149\0\u1184"+
    "\0\u11bf\0\u01d8\0\u11fa\0\u1235\0\u01d8\0\u1270\0\u12ab\0\u12e6"+
    "\0\u1321\0\u135c\0\u1397\0\u13d2\0\u140d\0\u01d8\0\u01d8\0\u1448"+
    "\0\u01d8\0\u1483\0\u14be\0\u14f9\0\u1534\0\u01d8\0\u01d8\0\u01d8"+
    "\0\u156f\0\u01d8\0\u01d8\0\u01d8\0\u15aa\0\u15e5\0\u1620\0\u01d8"+
    "\0\u01d8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\2\12\1\13\1\14\1\12\1\15\1\12\1\16\1\17"+
    "\1\20\1\12\1\21\1\22\3\12\1\23\1\12\1\24"+
    "\1\12\1\25\3\12\1\26\3\12\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\12\1\53\75\0\1\3\44\0\1\54\22\0"+
    "\1\55\3\0\1\4\67\0\5\5\1\0\65\5\5\56"+
    "\1\0\1\57\64\56\5\60\1\0\1\60\1\61\63\60"+
    "\1\0\2\12\5\0\1\12\1\62\34\12\23\0\2\12"+
    "\1\0\2\12\5\0\36\12\23\0\2\12\1\0\2\12"+
    "\5\0\6\12\1\63\14\12\1\64\12\12\23\0\2\12"+
    "\1\0\2\12\5\0\1\12\1\65\16\12\1\66\15\12"+
    "\23\0\2\12\1\0\2\12\5\0\10\12\1\67\25\12"+
    "\23\0\2\12\1\0\2\12\5\0\1\70\35\12\23\0"+
    "\2\12\1\0\2\12\5\0\5\12\1\71\2\12\1\72"+
    "\25\12\23\0\2\12\1\0\2\12\5\0\1\12\1\73"+
    "\34\12\23\0\2\12\1\0\2\12\5\0\11\12\1\74"+
    "\24\12\23\0\2\12\1\0\2\12\5\0\5\12\1\75"+
    "\30\12\23\0\2\12\1\0\2\12\5\0\20\12\1\76"+
    "\15\12\23\0\2\12\1\0\2\12\5\0\1\12\1\77"+
    "\11\12\1\100\22\12\23\0\2\12\1\0\2\12\5\0"+
    "\26\12\1\101\7\12\23\0\2\12\1\0\2\12\5\0"+
    "\32\12\1\102\3\12\23\0\2\12\1\0\2\12\5\0"+
    "\32\12\1\103\3\12\23\0\2\12\46\0\1\104\1\105"+
    "\11\0\1\104\13\0\1\106\44\0\1\107\11\0\1\110"+
    "\61\0\1\107\10\0\1\110\72\0\1\110\65\0\1\111"+
    "\4\0\1\110\66\0\1\112\73\0\1\112\75\0\1\104"+
    "\71\0\2\104\12\0\1\12\1\55\5\0\36\12\23\0"+
    "\2\12\2\0\1\113\72\0\1\114\67\0\1\115\1\0"+
    "\2\12\5\0\2\12\1\116\33\12\23\0\2\12\1\0"+
    "\2\12\5\0\7\12\1\117\26\12\23\0\2\12\1\0"+
    "\2\12\5\0\15\12\1\120\20\12\23\0\2\12\1\0"+
    "\2\12\5\0\5\12\1\121\30\12\23\0\2\12\1\0"+
    "\2\12\5\0\17\12\1\122\16\12\23\0\2\12\1\0"+
    "\2\12\5\0\24\12\1\123\11\12\23\0\2\12\1\0"+
    "\2\12\5\0\21\12\1\124\14\12\23\0\2\12\1\0"+
    "\2\12\5\0\7\12\1\125\6\12\1\126\17\12\23\0"+
    "\2\12\1\0\2\12\5\0\13\12\1\127\22\12\23\0"+
    "\2\12\1\0\2\12\5\0\10\12\1\130\25\12\23\0"+
    "\2\12\1\0\2\12\5\0\3\12\1\131\32\12\23\0"+
    "\2\12\1\0\2\12\5\0\3\12\1\132\32\12\23\0"+
    "\2\12\1\0\2\12\5\0\11\12\1\133\24\12\23\0"+
    "\2\12\1\0\2\12\5\0\6\12\1\134\27\12\23\0"+
    "\2\12\1\0\2\12\5\0\27\12\1\135\6\12\23\0"+
    "\2\12\1\0\2\12\5\0\33\12\1\136\2\12\23\0"+
    "\2\12\2\0\1\3\44\0\1\54\22\0\1\115\2\0"+
    "\1\137\44\0\1\54\22\0\1\115\2\0\1\114\67\0"+
    "\1\55\2\0\1\55\71\0\2\12\5\0\3\12\1\140"+
    "\32\12\23\0\2\12\1\0\2\12\5\0\10\12\1\141"+
    "\25\12\23\0\2\12\1\0\2\12\5\0\16\12\1\142"+
    "\17\12\23\0\2\12\1\0\2\12\5\0\11\12\1\143"+
    "\24\12\23\0\2\12\1\0\2\12\5\0\7\12\1\144"+
    "\26\12\23\0\2\12\1\0\2\12\5\0\10\12\1\145"+
    "\25\12\23\0\2\12\1\0\2\12\5\0\13\12\1\146"+
    "\22\12\23\0\2\12\1\0\2\12\5\0\10\12\1\147"+
    "\25\12\23\0\2\12\1\0\2\12\5\0\14\12\1\150"+
    "\21\12\23\0\2\12\1\0\2\12\5\0\5\12\1\151"+
    "\30\12\23\0\2\12\1\0\2\12\5\0\6\12\1\152"+
    "\27\12\23\0\2\12\1\0\2\12\5\0\1\153\35\12"+
    "\23\0\2\12\1\0\2\12\5\0\4\12\1\154\31\12"+
    "\23\0\2\12\1\0\2\12\5\0\30\12\1\155\5\12"+
    "\23\0\2\12\1\0\2\12\5\0\34\12\1\156\1\12"+
    "\23\0\2\12\2\0\1\137\44\0\1\54\22\0\1\55"+
    "\1\0\2\12\5\0\4\12\1\157\31\12\23\0\2\12"+
    "\1\0\2\12\5\0\2\12\1\160\33\12\23\0\2\12"+
    "\1\0\2\12\5\0\1\161\35\12\23\0\2\12\1\0"+
    "\2\12\5\0\5\12\1\162\30\12\23\0\2\12\1\0"+
    "\2\12\5\0\11\12\1\163\24\12\23\0\2\12\1\0"+
    "\2\12\5\0\5\12\1\164\30\12\23\0\2\12\1\0"+
    "\2\12\5\0\1\165\35\12\23\0\2\12\1\0\2\12"+
    "\5\0\22\12\1\166\13\12\23\0\2\12\1\0\2\12"+
    "\5\0\10\12\1\167\25\12\23\0\2\12\1\0\2\12"+
    "\5\0\7\12\1\170\26\12\23\0\2\12\1\0\2\12"+
    "\5\0\30\12\1\171\5\12\23\0\2\12\1\0\2\12"+
    "\5\0\5\12\1\172\30\12\23\0\2\12\1\0\2\12"+
    "\5\0\10\12\1\173\25\12\23\0\2\12\1\0\2\12"+
    "\5\0\10\12\1\174\25\12\23\0\2\12\1\0\2\12"+
    "\5\0\4\12\1\175\31\12\23\0\2\12\1\0\2\12"+
    "\5\0\6\12\1\176\27\12\23\0\2\12\1\0\2\12"+
    "\5\0\7\12\1\177\26\12\23\0\2\12\1\0\2\12"+
    "\5\0\10\12\1\200\25\12\23\0\2\12\1\0\2\12"+
    "\5\0\3\12\1\201\32\12\23\0\2\12\1\0\2\12"+
    "\5\0\1\202\35\12\23\0\2\12\1\0\2\12\5\0"+
    "\11\12\1\203\24\12\23\0\2\12\1\0\2\12\5\0"+
    "\17\12\1\204\16\12\23\0\2\12\1\0\2\12\5\0"+
    "\7\12\1\205\26\12\23\0\2\12\1\0\2\12\5\0"+
    "\1\12\1\206\34\12\23\0\2\12\1\0\2\12\5\0"+
    "\10\12\1\207\25\12\23\0\2\12\1\0\2\12\5\0"+
    "\6\12\1\210\27\12\23\0\2\12\1\0\2\12\5\0"+
    "\11\12\1\211\24\12\23\0\2\12";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5723];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\26\1\1\11\6\1\7\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\23\1\2\11"+
    "\1\1\4\11\1\0\1\1\1\0\21\1\1\0\52\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 35: 
          { lexeme=yytext(); return Break;
          }
        case 46: break;
        case 5: 
          { lexeme=yytext(); return Identificador;
          }
        case 47: break;
        case 28: 
          { lexeme=yytext(); return Modulo;
          }
        case 48: break;
        case 19: 
          { lexeme=yytext(); return P_coma;
          }
        case 49: break;
        case 15: 
          { lexeme=yytext(); return Llave_a;
          }
        case 50: break;
        case 41: 
          { lexeme=yytext(); return Logical;
          }
        case 51: break;
        case 32: 
          { lexeme=yytext(); return Else;
          }
        case 52: break;
        case 38: 
          { lexeme=yytext(); return Return;
          }
        case 53: break;
        case 4: 
          { lexeme=yytext(); return Linea;
          }
        case 54: break;
        case 29: 
          { lexeme=yytext(); return Raw;
          }
        case 55: break;
        case 30: 
          { lexeme=yytext(); return For;
          }
        case 56: break;
        case 34: 
          { lexeme=yytext(); return True;
          }
        case 57: break;
        case 31: 
          { lexeme=yytext(); return Next;
          }
        case 58: break;
        case 22: 
          { lexeme=yytext(); return In;
          }
        case 59: break;
        case 10: 
          { lexeme=yytext(); return Division;
          }
        case 60: break;
        case 6: 
          { lexeme = yytext(); return Op_relacional;
          }
        case 61: break;
        case 12: 
          { lexeme=yytext(); return Op_logico;
          }
        case 62: break;
        case 27: 
          { lexeme = yytext(); return Op_atribucion;
          }
        case 63: break;
        case 26: 
          { lexeme = yytext(); return Op_incremento;
          }
        case 64: break;
        case 2: 
          { lexeme=yytext(); return Numero;
          }
        case 65: break;
        case 16: 
          { lexeme=yytext(); return Llave_c;
          }
        case 66: break;
        case 24: 
          { lexeme=yytext(); return NA;
          }
        case 67: break;
        case 13: 
          { lexeme=yytext(); return Parentesis_a;
          }
        case 68: break;
        case 37: 
          { lexeme=yytext(); return False;
          }
        case 69: break;
        case 17: 
          { lexeme = yytext(); return Corchete_a;
          }
        case 70: break;
        case 20: 
          { lexeme=yytext(); return NumeroReal;
          }
        case 71: break;
        case 21: 
          { lexeme=yytext(); return Cadena;
          }
        case 72: break;
        case 33: 
          { lexeme=yytext(); return Main;
          }
        case 73: break;
        case 7: 
          { lexeme=yytext(); return Resta;
          }
        case 74: break;
        case 11: 
          { lexeme=yytext(); return Potencia;
          }
        case 75: break;
        case 39: 
          { lexeme=yytext(); return Repeat;
          }
        case 76: break;
        case 44: 
          { lexeme=yytext(); return Function;
          }
        case 77: break;
        case 45: 
          { lexeme=yytext(); return Character;
          }
        case 78: break;
        case 14: 
          { lexeme=yytext(); return Parentesis_c;
          }
        case 79: break;
        case 40: 
          { lexeme=yytext(); return Double;
          }
        case 80: break;
        case 9: 
          { lexeme=yytext(); return Multiplicacion;
          }
        case 81: break;
        case 18: 
          { lexeme = yytext(); return Corchete_c;
          }
        case 82: break;
        case 1: 
          { return ERROR;
          }
        case 83: break;
        case 43: 
          { lexeme=yytext(); return Complex;
          }
        case 84: break;
        case 42: 
          { lexeme=yytext(); return Integer;
          }
        case 85: break;
        case 25: 
          { lexeme=yytext(); return Igual;
          }
        case 86: break;
        case 36: 
          { lexeme=yytext(); return While;
          }
        case 87: break;
        case 3: 
          { /*Ignore*/
          }
        case 88: break;
        case 23: 
          { lexeme=yytext(); return If;
          }
        case 89: break;
        case 8: 
          { lexeme=yytext(); return Suma;
          }
        case 90: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
