
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 25 14:21:28 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Integer = 8;
  public static final int Function = 2;
  public static final int Parentesis_c = 5;
  public static final int Parentesis_a = 4;
  public static final int EOF = 0;
  public static final int P_coma = 10;
  public static final int Llave_c = 7;
  public static final int Identificador = 9;
  public static final int Main = 3;
  public static final int error = 1;
  public static final int Llave_a = 6;
  public static final int Igual = 11;
  public static final int Numero = 12;
}

