
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 28 19:34:56 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 5;
  public static final int Parentesis_a = 4;
  public static final int Suma = 21;
  public static final int Character = 15;
  public static final int Numero = 12;
  public static final int True = 17;
  public static final int Function = 2;
  public static final int Identificador = 9;
  public static final int Integer = 8;
  public static final int False = 18;
  public static final int Llave_c = 7;
  public static final int Double = 13;
  public static final int Llave_a = 6;
  public static final int P_coma = 10;
  public static final int Main = 3;
  public static final int Cadena = 16;
  public static final int EOF = 0;
  public static final int Division = 20;
  public static final int Resta = 22;
  public static final int error = 1;
  public static final int Igual = 11;
  public static final int NumeroReal = 23;
  public static final int Multiplicacion = 19;
  public static final int Logical = 14;
}

