/* The following code was generated by JFlex 1.4.3 on 28/02/23 03:35 PM */

package proyecto1;
import static proyecto1.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 28/02/23 03:35 PM from the specification file
 * <tt>D:/ricar/Documents/UP/8/Compiladores/1/Proyecto1/src/proyecto1/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\3\22\0\1\3\1\55\1\6\1\4"+
    "\1\0\1\52\1\53\1\6\1\60\1\61\1\47\1\46\1\3\1\45"+
    "\1\70\1\50\12\2\1\0\1\66\1\44\1\57\1\56\2\0\1\40"+
    "\3\67\1\36\1\37\5\67\1\41\1\67\1\43\3\67\1\34\1\42"+
    "\1\33\1\35\5\67\1\64\1\0\1\65\1\51\1\1\1\0\1\14"+
    "\1\23\1\13\1\21\1\17\1\32\1\11\1\27\1\12\1\67\1\31"+
    "\1\7\1\24\1\15\1\10\1\25\1\67\1\20\1\67\1\16\1\22"+
    "\1\67\1\30\1\26\2\67\1\62\1\54\1\63\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\5\15\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\1\3\15\1\7"+
    "\1\1\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\6\1\0\1\25\1\6\1\26\1\27\14\6\1\30"+
    "\1\7\1\31\1\2\1\32\1\33\1\34\1\15\1\0"+
    "\1\25\1\0\5\6\1\35\5\6\1\36\3\6\1\0"+
    "\4\6\1\37\6\6\1\40\10\6\1\41\1\42\1\6"+
    "\1\43\4\6\1\44\1\45\2\6\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\71\0\71\0\u011d"+
    "\0\u0156\0\u018f\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5"+
    "\0\u031e\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad"+
    "\0\u04ad\0\71\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0591"+
    "\0\71\0\71\0\71\0\71\0\71\0\71\0\71\0\u0603"+
    "\0\u063c\0\u0675\0\u06ae\0\u06e7\0\u0156\0\u0720\0\u0759\0\u0792"+
    "\0\u07cb\0\u0804\0\u083d\0\u0876\0\u08af\0\u08e8\0\u0921\0\u095a"+
    "\0\u0993\0\u0156\0\71\0\71\0\u09cc\0\71\0\71\0\71"+
    "\0\71\0\u0a05\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b"+
    "\0\u0b94\0\u0156\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1\0\u0156"+
    "\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79"+
    "\0\u0156\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\u0156"+
    "\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197"+
    "\0\u0156\0\u0156\0\u11d0\0\u0156\0\u1209\0\u1242\0\u127b\0\u12b4"+
    "\0\u0156\0\u0156\0\u12ed\0\u1326\0\u0156";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\5\1\6\1\7\1\10\2\11"+
    "\1\12\1\13\1\11\1\14\2\11\1\15\1\16\1\11"+
    "\1\17\4\11\1\20\1\11\1\21\1\22\3\11\1\23"+
    "\3\11\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\11\1\50\73\0"+
    "\1\3\42\0\1\51\22\0\1\52\3\0\1\4\65\0"+
    "\5\5\1\0\63\5\1\0\2\11\4\0\1\11\1\53"+
    "\33\11\23\0\2\11\1\0\2\11\4\0\35\11\23\0"+
    "\2\11\1\0\2\11\4\0\6\11\1\54\14\11\1\55"+
    "\11\11\23\0\2\11\1\0\2\11\4\0\1\11\1\56"+
    "\16\11\1\57\14\11\23\0\2\11\1\0\2\11\4\0"+
    "\10\11\1\60\24\11\23\0\2\11\1\0\2\11\4\0"+
    "\5\11\1\61\2\11\1\62\24\11\23\0\2\11\1\0"+
    "\2\11\4\0\1\11\1\63\33\11\23\0\2\11\1\0"+
    "\2\11\4\0\11\11\1\64\23\11\23\0\2\11\1\0"+
    "\2\11\4\0\20\11\1\65\14\11\23\0\2\11\1\0"+
    "\2\11\4\0\1\11\1\66\11\11\1\67\21\11\23\0"+
    "\2\11\1\0\2\11\4\0\25\11\1\70\7\11\23\0"+
    "\2\11\1\0\2\11\4\0\31\11\1\71\3\11\23\0"+
    "\2\11\1\0\2\11\4\0\31\11\1\72\3\11\23\0"+
    "\2\11\44\0\1\73\1\74\11\0\1\73\13\0\1\75"+
    "\42\0\1\76\11\0\1\77\57\0\1\76\10\0\1\77"+
    "\70\0\1\77\63\0\1\100\4\0\1\77\64\0\1\101"+
    "\71\0\1\101\73\0\1\73\67\0\2\73\12\0\1\11"+
    "\1\52\4\0\35\11\23\0\2\11\2\0\1\102\70\0"+
    "\1\103\65\0\1\104\1\0\2\11\4\0\2\11\1\105"+
    "\32\11\23\0\2\11\1\0\2\11\4\0\7\11\1\106"+
    "\25\11\23\0\2\11\1\0\2\11\4\0\15\11\1\107"+
    "\17\11\23\0\2\11\1\0\2\11\4\0\5\11\1\110"+
    "\27\11\23\0\2\11\1\0\2\11\4\0\17\11\1\111"+
    "\15\11\23\0\2\11\1\0\2\11\4\0\21\11\1\112"+
    "\13\11\23\0\2\11\1\0\2\11\4\0\7\11\1\113"+
    "\6\11\1\114\16\11\23\0\2\11\1\0\2\11\4\0"+
    "\13\11\1\115\21\11\23\0\2\11\1\0\2\11\4\0"+
    "\10\11\1\116\24\11\23\0\2\11\1\0\2\11\4\0"+
    "\3\11\1\117\31\11\23\0\2\11\1\0\2\11\4\0"+
    "\11\11\1\120\23\11\23\0\2\11\1\0\2\11\4\0"+
    "\6\11\1\121\26\11\23\0\2\11\1\0\2\11\4\0"+
    "\26\11\1\122\6\11\23\0\2\11\1\0\2\11\4\0"+
    "\32\11\1\123\2\11\23\0\2\11\2\0\1\3\42\0"+
    "\1\51\22\0\1\104\2\0\1\124\42\0\1\51\22\0"+
    "\1\104\2\0\1\103\65\0\1\52\2\0\1\52\67\0"+
    "\2\11\4\0\3\11\1\125\31\11\23\0\2\11\1\0"+
    "\2\11\4\0\10\11\1\126\24\11\23\0\2\11\1\0"+
    "\2\11\4\0\16\11\1\127\16\11\23\0\2\11\1\0"+
    "\2\11\4\0\11\11\1\130\23\11\23\0\2\11\1\0"+
    "\2\11\4\0\7\11\1\131\25\11\23\0\2\11\1\0"+
    "\2\11\4\0\13\11\1\132\21\11\23\0\2\11\1\0"+
    "\2\11\4\0\10\11\1\133\24\11\23\0\2\11\1\0"+
    "\2\11\4\0\14\11\1\134\20\11\23\0\2\11\1\0"+
    "\2\11\4\0\5\11\1\135\27\11\23\0\2\11\1\0"+
    "\2\11\4\0\1\136\34\11\23\0\2\11\1\0\2\11"+
    "\4\0\4\11\1\137\30\11\23\0\2\11\1\0\2\11"+
    "\4\0\27\11\1\140\5\11\23\0\2\11\1\0\2\11"+
    "\4\0\33\11\1\141\1\11\23\0\2\11\2\0\1\124"+
    "\42\0\1\51\22\0\1\52\1\0\2\11\4\0\4\11"+
    "\1\142\30\11\23\0\2\11\1\0\2\11\4\0\2\11"+
    "\1\143\32\11\23\0\2\11\1\0\2\11\4\0\1\144"+
    "\34\11\23\0\2\11\1\0\2\11\4\0\5\11\1\145"+
    "\27\11\23\0\2\11\1\0\2\11\4\0\11\11\1\146"+
    "\23\11\23\0\2\11\1\0\2\11\4\0\5\11\1\147"+
    "\27\11\23\0\2\11\1\0\2\11\4\0\1\150\34\11"+
    "\23\0\2\11\1\0\2\11\4\0\22\11\1\151\12\11"+
    "\23\0\2\11\1\0\2\11\4\0\10\11\1\152\24\11"+
    "\23\0\2\11\1\0\2\11\4\0\7\11\1\153\25\11"+
    "\23\0\2\11\1\0\2\11\4\0\27\11\1\154\5\11"+
    "\23\0\2\11\1\0\2\11\4\0\5\11\1\155\27\11"+
    "\23\0\2\11\1\0\2\11\4\0\10\11\1\156\24\11"+
    "\23\0\2\11\1\0\2\11\4\0\10\11\1\157\24\11"+
    "\23\0\2\11\1\0\2\11\4\0\4\11\1\160\30\11"+
    "\23\0\2\11\1\0\2\11\4\0\6\11\1\161\26\11"+
    "\23\0\2\11\1\0\2\11\4\0\7\11\1\162\25\11"+
    "\23\0\2\11\1\0\2\11\4\0\10\11\1\112\24\11"+
    "\23\0\2\11\1\0\2\11\4\0\3\11\1\163\31\11"+
    "\23\0\2\11\1\0\2\11\4\0\1\112\34\11\23\0"+
    "\2\11\1\0\2\11\4\0\11\11\1\112\23\11\23\0"+
    "\2\11\1\0\2\11\4\0\17\11\1\112\15\11\23\0"+
    "\2\11\1\0\2\11\4\0\7\11\1\143\25\11\23\0"+
    "\2\11\1\0\2\11\4\0\1\11\1\164\33\11\23\0"+
    "\2\11\1\0\2\11\4\0\6\11\1\165\26\11\23\0"+
    "\2\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4959];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\2\11\22\1\1\11\6\1\7\11"+
    "\1\1\1\0\21\1\2\11\1\1\4\11\1\0\1\1"+
    "\1\0\17\1\1\0\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 33: 
          { lexeme=yytext(); return Break;
          }
        case 39: break;
        case 6: 
          { lexeme=yytext(); return Identificador;
          }
        case 40: break;
        case 28: 
          { lexeme=yytext(); return Modulo;
          }
        case 41: break;
        case 20: 
          { lexeme=yytext(); return P_coma;
          }
        case 42: break;
        case 16: 
          { lexeme=yytext(); return Llave_a;
          }
        case 43: break;
        case 36: 
          { lexeme=yytext(); return Return;
          }
        case 44: break;
        case 4: 
          { return Linea;
          }
        case 45: break;
        case 30: 
          { lexeme=yytext(); return For;
          }
        case 46: break;
        case 32: 
          { lexeme=yytext(); return TRUE;
          }
        case 47: break;
        case 35: 
          { lexeme=yytext(); return FALSE;
          }
        case 48: break;
        case 31: 
          { lexeme=yytext(); return Next;
          }
        case 49: break;
        case 22: 
          { lexeme=yytext(); return In;
          }
        case 50: break;
        case 11: 
          { lexeme=yytext(); return Division;
          }
        case 51: break;
        case 7: 
          { lexeme = yytext(); return Op_relacional;
          }
        case 52: break;
        case 13: 
          { lexeme=yytext(); return Op_logico;
          }
        case 53: break;
        case 27: 
          { lexeme = yytext(); return Op_atribucion;
          }
        case 54: break;
        case 26: 
          { lexeme = yytext(); return Op_incremento;
          }
        case 55: break;
        case 2: 
          { lexeme=yytext(); return Numero;
          }
        case 56: break;
        case 17: 
          { lexeme=yytext(); return Llave_c;
          }
        case 57: break;
        case 24: 
          { lexeme=yytext(); return NA;
          }
        case 58: break;
        case 14: 
          { lexeme=yytext(); return Parentesis_a;
          }
        case 59: break;
        case 5: 
          { lexeme=yytext(); return Comillas;
          }
        case 60: break;
        case 18: 
          { lexeme = yytext(); return Corchete_a;
          }
        case 61: break;
        case 21: 
          { lexeme=yytext(); return NumeroReal;
          }
        case 62: break;
        case 8: 
          { lexeme=yytext(); return Resta;
          }
        case 63: break;
        case 29: 
          { lexeme=yytext(); return T_dato;
          }
        case 64: break;
        case 12: 
          { lexeme=yytext(); return Potencia;
          }
        case 65: break;
        case 37: 
          { lexeme=yytext(); return Repeat;
          }
        case 66: break;
        case 38: 
          { lexeme=yytext(); return Function;
          }
        case 67: break;
        case 15: 
          { lexeme=yytext(); return Parentesis_c;
          }
        case 68: break;
        case 10: 
          { lexeme=yytext(); return Multiplicacion;
          }
        case 69: break;
        case 19: 
          { lexeme = yytext(); return Corchete_c;
          }
        case 70: break;
        case 1: 
          { return ERROR;
          }
        case 71: break;
        case 25: 
          { lexeme=yytext(); return Igual;
          }
        case 72: break;
        case 34: 
          { lexeme=yytext(); return While;
          }
        case 73: break;
        case 3: 
          { /*Ignore*/
          }
        case 74: break;
        case 23: 
          { lexeme=yytext(); return If;
          }
        case 75: break;
        case 9: 
          { lexeme=yytext(); return Suma;
          }
        case 76: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
